version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8888:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ~/Desktop/db:/var/lib/mysql
    ports:
      - 7777:3306
    environment:
      MYSQL_DATABASE: booking
      MYSQL_ROOT_PASSWORD: root
