version: "3"
services:
  springboot-app:
    image: springboot-app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 8888:8080


  mysqldb:
    container_name: mysqldb
    image: mysql
    env_file:
      - .env
    volumes:
      - ~/Desktop/db:/var/lib/mysql
    ports:
      - 7777:3306

